before:
  hooks:
  - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    main: cmd/gopssh/main.go
    binary: gopssh
    goos:
      - linux
      - darwin
    goarch:
      - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
    - 'masahide/gopssh:{{ .Tag }}'
    - 'masahide/gopssh:v{{ .Major }}.{{ .Minor }}'
    - 'masahide/gopssh:latest'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

brews:
  - github:
      owner: masahide
      name: gopssh
    folder: Formula
    homepage:  https://github.com/masahide/gopssh
    description: parallel ssh client
    test: |
      system "#{bin}/gopssh -v"

nfpms:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/masahide/gopssh
    description: parallel ssh client
    maintainer: YAMASAKI Masahide <masahide.y@gmail.com>
    license: MIT
    vendor: YAMASAKI Masahide
    formats:
      - deb
      - rpm
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: parallel ssh client
    description: parallel ssh client
    grade: stable
    confinement: classic
