@startuml{gopssh}
'画像変換するときにここで指定したファイル名になる。

title gopssh処理図

hide footbox
'シーケンスの縦線の下部にシーケンスボックスを出すかどうか指定する。よほど長いものでない限りいらないだろう

actor コンソール as user
'actorにすると人っぽい見かけになる

participant "Command main" as main
participant "Connection worker" as conWorker
participant server as server
'participantにすると四角になる


group 接続のみ
	user -> main : 接続先リスト

	main -> user : pipeファイルを返す

	main -> conWorker : 接続先の数だけ起動
	activate conWorker

	conWorker -> server : ssh接続のみ
	activate server

	server -> conWorker : 接続完了
end

group コマンド発行
	user -> main : コマンド&stdin

	main -> conWorker : コマンド&stdin

	conWorker-> server: session作成&コマンド発行
	activate server #DarkSalmon

	server -> conWorker: stdout,stderr
	deactivate server

	conWorker -> main : stdout,stderr
	main -> user : stdout,stderr
end


