# This file was generated by GoReleaser. DO NOT EDIT.
class Gopssh < Formula
  desc "parallel ssh client"
  homepage "https://github.com/masahide/gopssh"
  url "https://github.com/masahide/gopssh/releases/download/v0.5.3/gopssh_Darwin_x86_64.tar.gz"
  version "0.5.3"
  sha256 "dbd85db1be71adb5ae5f392a0688283a6397d46f5a0fc5a3d77856e3d673247e"

  def install
    bin.install "gopssh"
  end

  test do
    system "#{bin}/gopssh -v"
  end
end
