# This file was generated by GoReleaser. DO NOT EDIT.
class Gopssh < Formula
  desc "parallel ssh client"
  homepage "https://github.com/masahide/gopssh"
  url "https://github.com/masahide/gopssh/releases/download/v0.5.4/gopssh_Darwin_x86_64.tar.gz"
  version "0.5.4"
  sha256 "a9ad765ebe8919bd429cb64fe35b79d21202b074559ffa824ee23a3972cff44d"

  def install
    bin.install "gopssh"
  end

  test do
    system "#{bin}/gopssh -v"
  end
end
