name: Go package

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GO_VERSION: '1.19'
  APP_NAME: 'gopssh'
  MAIN_GO: 'cmd/gopssh/main.go'

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: go test -v ./...

      - name: Get the info
        id: info
        run: |
          echo "ver=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: show info
        run: |
          echo "version: ${{ steps.info.outputs.ver }}" >> $GITHUB_STEP_SUMMARY
          echo "commit:  ${{ steps.info.outputs.hash }}" >> $GITHUB_STEP_SUMMARY
          echo "date:    $(date --iso-8601=seconds)" >> $GITHUB_STEP_SUMMARY

      - name: Build
        run: go build -v -ldflags "-X main.version=${{ steps.info.outputs.ver }} -X main.commit=${{ steps.info.outputs.hash }} -X main.date=$(date --iso-8601=seconds)" -o .bin/${{ env.APP_NAME }} ${{ env.MAIN_GO }}

      - name: Build Linux RPM Packages
        id: rpm
        run: echo file=$(go run -ldflags "-X main.name=${{ env.APP_NAME }} -X main.release=1 -X main.version=${{ steps.info.outputs.ver }} -X main.hash=${{ steps.info.outputs.hash }} -X main.arch=x86_64" cmd/rpmpack/main.go) >> $GITHUB_OUTPUT

      - name: Build Linux DEB Packages
        id: deb
        run: echo file=$(go run -ldflags "-X main.name=${{ env.APP_NAME }} -X main.version=${{ steps.info.outputs.ver }} -X main.arch=amd64" cmd/debpack/main.go) >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.rpm.outputs.file }}
          path: |
            ./*.rpm

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.deb.outputs.file }}
          path: |
            ./*.deb

      - name: show info
        run: |
          echo "ls -la" >> $GITHUB_STEP_SUMMARY
          ls -la >> $GITHUB_STEP_SUMMARY

