name: Go test

on: [push]

env:
  GO_VERSION: '1.19'

jobs:
  go-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v cmd/gopssh/main.go

      - name: Test
        run: go test -v ./...

